const path = require('path');

module.exports = {
  extends: [
    'angular-tslint-rules',
    'rxjs-tslint-rules',
    'tslint-config-airbnb',
    'tslint-angular',
    'tslint-config-prettier',
    'tslint-clean-code',
    'tslint-plugin-prettier',
    'tslint-override',
    'tslint-sonarts',
  ],
  linterOptions: {
    exclude: ['node_modules/**', 'dist/**'],
  },
  rulesDirectory: [
    path.join(path.dirname(require.resolve('@nrwl/workspace')), 'src/tslint'),
    path.join(path.dirname(require.resolve('codelyzer')), './'),
  ],
  rules: {
    'arrow-return-shorthand': true,
    'await-promise': false,
    'array-type': false,
    'callable-types': true,
    'class-name': true,
    curly: [true, 'ignore-same-line'],
    deprecation: {
      severity: 'warn',
    },
    'explicit-override': [
      true,
      'decorator',
      'pascal-case-fixer',
      'new-line-after-decorators-and-tags',
      'angular-syntax-fixer',
    ],
    forin: true,
    'import-blacklist': [true, 'rxjs/Rx'],
    'interface-over-type-literal': true,
    'member-access': true,
    'member-ordering': [
      true,
      {
        order: ['static-field', 'instance-field', 'static-method', 'instance-method'],
      },
    ],
    'no-arg': true,
    'no-bitwise': true,
    'no-console': [true, 'debug', 'info', 'time', 'timeEnd', 'trace'],
    'no-construct': true,
    'no-debugger': true,
    'no-duplicate-super': true,
    'no-floating-promises': false,
    'no-empty': false,
    'no-empty-interface': true,
    'no-eval': true,
    'no-inferrable-types': [true, 'ignore-params'],
    'no-implicit-dependencies': false,
    'no-import-side-effect': [
      true,
      {
        'ignore-module': '(angular-register|commands|jest-preset-angular|zone)$',
      },
    ],
    'no-misused-new': true,
    'no-non-null-assertion': true,
    'no-null-keyword': false,
    'no-shadowed-variable': true,
    'no-string-literal': false,
    'no-string-throw': true,
    'no-switch-case-fall-through': true,
    'no-void-expression': [true, 'ignore-arrow-function-shorthand'],
    'no-unbound-method': false,
    'no-unnecessary-initializer': true,
    'no-unused-expression': true,
    'no-var-keyword': true,
    'object-literal-sort-keys': false,
    'prefer-const': true,
    'prefer-inline-decorator': false,
    prettier: true,
    radix: true,
    'triple-equals': [true, 'allow-null-check'],
    'unified-signatures': true,
    'unnecessary-constructor': false,
    'variable-name': false,
    'nx-enforce-module-boundaries': [
      true,
      {
        allow: [],
        depConstraints: [
          {
            sourceTag: '*',
            onlyDependOnLibsWithTags: ['*'],
          },
        ],
        enforceBuildableLibDependency: true,
      },
    ],
    'directive-selector': [true, 'attribute', 'app', 'camelCase'],
    'component-selector': [true, 'element', 'app', 'kebab-case'],
    'no-conflicting-lifecycle': true,
    'no-host-metadata-property': true,
    'no-input-rename': true,
    'no-inputs-metadata-property': true,
    'no-output-native': true,
    'no-output-on-prefix': true,
    'no-output-rename': true,
    'no-outputs-metadata-property': true,
    'template-banana-in-box': true,
    'template-i18n': false,
    'template-no-negated-async': true,
    'use-lifecycle-interface': true,
    'use-pipe-transform-interface': true,
  },
};
